name:                EtaNet
version:             0.1.0.0
github:              "githubuser/EtaNet"
license:             BSD3
author:              "Luke Tyler"
maintainer:          "example@example.com"
copyright:           "2022 Luke Tyler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/EtaNet#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- matrix

library:
  source-dirs: src

executables:
  EtaNet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EtaNet

tests:
  EtaNet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EtaNet
